### ISSUE TITLE
Issue: need to send 2 time the print update from orca slicer to start the print

### ISSUE THREAD

**Issue by ducati1198** [jbatonnet/Rinkhals#9]
Issue is that i need to send 2 time  the upload and print (orca slicer) to startup the printer. When sending the first one I see it uploading in Mainsail but doesn’t not start . Second attempt it start printing. Moonraker log 
[moonraker2.log](https://github.com/user-attachments/files/18224629/moonraker2.log)

**Comment by jbatonnet** [comment]
Hi, the log you uploaded shows that you are using DuckPro right now:
data_path: /useremain/home/**ytka**/printer_data
Might be some old logs from DuckPro.

Using Rinhals, all logs are consolidated in **/useremain/rinkhals/[VERSION]/*.log**
I created a tool to easily get all logs for me or anyone to debug a situation, the SWU debug-bundle tool.

Please grab the **tools-debug-bundle.swu** tool in this page: https://github.com/jbatonnet/Rinkhals/actions/runs/12420701052
Here are the instructions on how to use: https://github.com/jbatonnet/Rinkhals?tab=readme-ov-file#swu-tools

But basically flash it as **update.swu**, you'll hear two beeps and then you'll have a debug-bundle.zip file on the USB drive.
You can check, but there should not be any personnal or machine-specific info.
Then you can just upload the file here.

**Comment by ducati1198** [comment]
Wow that weird. I got it directly on mailsail and dont have duckpro install, its a frensh install, i will upload your logs soon theres something printing right know 

My useredate folder with no duckpro:

![IMG_6442](https://github.com/user-attachments/assets/75acb7ff-db7e-45fb-82ba-cf8b75286366)

**Comment by ducati1198** [comment]
Where are your log. I got them with sftp in your folder as mentioned

[Logs.zip](https://github.com/user-attachments/files/18224779/Logs.zip)

**Comment by jbatonnet** [comment]
Ok I see the 2 upload&print calls from Orca:
![image](https://github.com/user-attachments/assets/d0f7fcd2-8f5d-4dcc-8727-8bfb90d63af5)

But I don't see any errors in the logs.
TBH, the proxy instantly sends the print command to the printer, but it can take some time before actually seeing the print start. I use it almost everyday directly from Orca, and it can take 3~6 seconds to start, but always starts on mine. Next time try to wait a little bit more.

I'll try to add more logs in the proxy, timestamps and maybe monitor the printer response to the request. There might be some clues here.

**Comment by ducati1198** [comment]
Thanks
How can i change the time i. The system for montreal

**Comment by jbatonnet** [comment]
I published a new release with more logs, and if the printer fails printing it will be reported and shown in Orca:
https://github.com/jbatonnet/Rinkhals/releases/tag/20241223_01

**Comment by m3rguez0o** [comment]
Hello!
Just installed your latest release 20241223_01 and I have some comments.
- there was a homing /X problem on my printer it went to the right and "cracked" for some seconds and gave me an error message on the printer, I rebooted the printer, homing again in mainsail (it start automatically :) ) same thing this time I xait a little more seconds, it stop and then go to the center, it seems ok.
- when clicking print in orca, it give an internal error 500 something wrong with the server?
- if i save the gcode and then upload and print in mainsail, it re-do the wrong thing with the x axis all way right then crack with an error message on the printer and in mainsail.
- another thing I noticed, on the previous release, the camera was real time with no lag and 14/15fps, in this release it is very laggy (I have the time to go walk back to my desk, sit on my chair and I see my hand on the screen) and reach maximum 6 fps on mine.

![Capture d'écran 2024-12-23 102711](https://github.com/user-attachments/assets/dd0e49a6-56d5-4e96-b5d2-7666faace0d7)
![Capture d'écran 2024-12-23 103511](https://github.com/user-attachments/assets/d5d92f7d-c994-4332-a7db-952f029c839e)

https://github.com/user-attachments/assets/de0734c7-0955-40ee-a302-b555a500f5da

**Comment by m3rguez0o** [comment]
Here it is:
[debug-bundle.zip](https://github.com/user-attachments/files/18230676/debug-bundle.zip)

I tried to go back to 20241218_01 release but the camera doesn't go over 6fps anymore...
Homing function work again.
Camera toggle in the menu don't work, it is always on.

Here is the log when starting rinkhals:

```
PowerShell 7.4.6
PS C:\Users\m3rgu> ssh root@192.168.1.45 -p2222
root@192.168.1.45's password:
root@Rockchip:~# cd ..
root@Rockchip:/# ls
var            tmp            root           oem            lib64          dev            ac_app
usr            sys            rockchip_test  mnt            lib32          data
useremain      sbin           proc           media          lib            bin
userdata       run            opt            linuxrc        etc            ac_lib
root@Rockchip:/# cd useremain
root@Rockchip:/useremain# cd rinkhals
root@Rockchip:/useremain/rinkhals# ls
20241219_01                               rinkhals.log
install.log                               20241223_01
3a8dbab49e39bab6a44d94c8addefc3e351d35f5  start.sh.patch
start-rinkhals.sh                         20241218_01
root@Rockchip:/useremain/rinkhals# ls -a
20241219_01                               start-rinkhals.sh
.current                                  rinkhals.log
.version                                  20241223_01
install.log                               .
3a8dbab49e39bab6a44d94c8addefc3e351d35f5  start.sh.patch
..                                        20241218_01
root@Rockchip:/useremain/rinkhals# cat .version
20241218_01
root@Rockchip:/useremain/rinkhals# ./start-rinkhals
-sh: ./start-rinkhals: not found
root@Rockchip:/useremain/rinkhals# ./start-rinkhals.sh

Starting Rinkhals...
Rinkhals startup was called from -sh (1381)
Rinkhals version 20241218_01 selected

Starting Rinkhals...

          ██████████
        ██          ██
        ██            ██
      ██  ██      ██  ██
      ██  ██      ██  ░░██
      ██              ░░██
        ██░░░░░░░░░░░░██
          ██████████████
      ████    ██    ░░████
    ██      ██      ░░██░░██
  ██    ██░░░░░░░░░░██  ░░░░██
  ██░░    ██████████    ░░██░░██
  ██░░                  ░░██░░██
    ██░░░░░░░░░░░░░░░░░░████░░██
      ██████████████████    ██

 --------------------------------------------------
| Kobra firmware: 2.3.5.3
| Rinkhals version: 20241218_01
| Rinkhals root: /useremain/rinkhals/20241218_01
 --------------------------------------------------

> Fixing permissions...
> Starting SSH...
Killing 1265 (/tmp/swu-ssh/lib/ld-linux-armhf.so.3/tmp/swu-ssh/usr/sbin/dropbear-F-E-a-p2222-P/tmp/swu-ssh/dropbear.pid-r/tmp/swu-ssh/etc/dropbear/dropbear_rsa_host_key)
> Starting ADB...
> Stopping Klipper...
Killing 368 (./K3SysUi)
Killing 438 (./gkcam)
Killing 367 (./gkapi)
Killing 354 (./gklib-a/tmp/unix_uds1printer.cfg)
> Preparing chroot...
> Starting Moonraker...
> Starting nginx...
> Starting mjpg-streamer...
> Restarting Klipper...
> Cleaning up...
Killing 1665 (/useremain/rinkhals/20241218_01/lib/ld-linux-armhf.so.3./usr/sbin/dropbear-F-E-a-p2222-P/tmp/dropbear_debug.pid-r./etc/dropbear/dropbear_rsa_host_key)

Rinkhals started
root@Rockchip:/useremain/rinkhals# ls
20241219_01                               start-rinkhals.sh                         start.sh.patch
install.log                               rinkhals.log                              20241218_01
3a8dbab49e39bab6a44d94c8addefc3e351d35f5  20241223_01
root@Rockchip:/useremain/rinkhals# cd useremain
-sh: cd: can't cd to useremain
root@Rockchip:/useremain/rinkhals# cd ..
root@Rockchip:/useremain# ls
rinkhals             app                  lost+found           update_swu           dev                  TestMainResult.json
root@Rockchip:/useremain# cd app
root@Rockchip:/useremain/app# ls
gk
root@Rockchip:/useremain/app# cd gk
root@Rockchip:/useremain/app/gk# ls
cert3         printer_data  gcodes        cert1
root@Rockchip:/useremain/app/gk# cd printer_data
root@Rockchip:/useremain/app/gk/printer_data# ls
logs
root@Rockchip:/useremain/app/gk/printer_data# cd ../..
root@Rockchip:/useremain/app# cd ..
root@Rockchip:/useremain# ls
rinkhals             app                  lost+found           update_swu           dev                  TestMainResult.json
root@Rockchip:/useremain# cd ..
root@Rockchip:/# ls
var            userdata       sbin           rockchip_test  oem            linuxrc        lib            data           ac_app
usr            tmp            run            proc           mnt            lib64          etc            bin
useremain      sys            root           opt            media          lib32          dev            ac_lib
root@Rockchip:/# cd userdata
root@Rockchip:/userdata# ls
wifi_cfg                        vpss_stresstest.sh              isp_stresstest.sh               channel.sh.1
rv1126_stresstest.sh            channel.1                       channel                         160x96.bmp
app                             rv1106_multi_cam_stresstest.sh  demo_vi_venc_stresstest.sh      ex_and_im.sh
multi_isp_stresstest.sh         rgn_stresstest.sh               rv1103_stresstest.sh            lost+found
venc_stresstest.sh              demo_vi_avs_venc_stresstest.sh  channel.sh                      192x96.bmp
ai_aenc_adec_ao_stresstes.sh    rv1106_stresstest.sh            avs_stresstest.sh
ex_and_im.sh.1                  ethaddr.txt                     rv1126_multi_cam_stresstest.sh
root@Rockchip:/userdata# cd app
root@Rockchip:/userdata/app# ls
collidingmice  certs          gk             kenv
root@Rockchip:/userdata/app# cd gk
root@Rockchip:/userdata/app/gk# ls
gkapi.1                             libc_helper.so                      Historylist.csv
restart_k3c.sh.bak                  printer.cfg.1                       gkapi
restart_k3c.sh.1                    start.sh                            config
start.sh.bak                        Translate                           restart_k3c.sh
printer_mutable_19700101000642.cfg  gkcam                               temperature_sensors.cfg
K3SysUi.1                           gklib.1                             version_log.txt
printer_mutable_19700101000922.cfg  start.sh.1                          gklib
printer_data                        printer.cfg                         gkcam.1
K3SysUi                             printer_mutable.cfg
gcodes                              version_log.txt.1
root@Rockchip:/userdata/app/gk# ./restart_k3c.sh
killall: gkcam: no process killed
Rinkhals is installed, starting...

Starting Rinkhals...
Rinkhals startup was called from /bin/sh./restart_k3c.sh (2620)
Rinkhals version 20241218_01 selected

Starting Rinkhals...

          ██████████
        ██          ██
        ██            ██
      ██  ██      ██  ██
      ██  ██      ██  ░░██
      ██              ░░██
        ██░░░░░░░░░░░░██
          ██████████████
      ████    ██    ░░████
    ██      ██      ░░██░░██
  ██    ██░░░░░░░░░░██  ░░░░██
  ██░░    ██████████    ░░██░░██
  ██░░                  ░░██░░██
    ██░░░░░░░░░░░░░░░░░░████░░██
      ██████████████████    ██

 --------------------------------------------------
| Kobra firmware: 2.3.5.3
| Rinkhals version: 20241218_01
| Rinkhals root: /useremain/rinkhals/20241218_01
 --------------------------------------------------

> Fixing permissions...
> Starting SSH...
CfgDat.IpAddr = 127.0.0.1
CfgDat.IpPort = 18086
CfgDat.LogPath = /ac_app
LogAttr.UartAttr.DevicePath is Null!
gkcam-->Nov  1 2024/14:34:02-main-67::LogInit ok:

gkcam-->Nov  1 2024/14:34:02-RpcFrameConnect-99::Addr:127.0.0.1
gkcam-->Nov  1 2024/14:34:02-RpcFrameConnect-100::Port:18086
gkcam-->Nov  1 2024/14:34:02-RpcFrameInit-204::RpcFrameInit: Init Success!
rockit log path (null), log_size = 0, can use export rt_log_path=, export rt_log_size= change
log_file = (nil)
RTVersion        14:51:29-998 {dump              :064} ---------------------------------------------------------
RTVersion        14:51:30-000 {dump              :065} rockit version: git-56434d252 Tue Apr 4 15:06:22 2023 +0800
RTVersion        14:51:30-001 {dump              :066} rockit building: built- 2023-04-04 15:22:18
RTVersion        14:51:30-001 {dump              :067} ---------------------------------------------------------
(null)           14:51:30-001 {log_level_init    :206}

 please use echo name=level > /tmp/rt_log_level set log level
        name: all cmpi mb sys vdec venc rgn vpss vgs tde avs wbc vo vi ai ao aenc adec
        log_level: 0 1 2 3 4 5 6

Server listening on port 0
rockit default level 4, can use export rt_log_level=x, x=0,1,2,3,4,5,6 change
(null)           14:51:30-004 {read_log_level    :097} text is all=4
(null)           14:51:30-004 {read_log_level    :099} module is all, log_level is 4
RTIsp3x          14:51:30-038 {ispInitDevice     :317} sensor name = Camera 1
RTIsp3x          14:51:30-043 {ispInitDevice     :320} sensor_index = 61
(null)           14:51:30-045 {monitor_log_level :148} #Start monitor_log_level thread, arg:(nil)
RTIsp3x          14:51:30-049 {getIspSubdevs     :100} rkisp_bypasspath entity name is NULL
RTIsp3x          14:51:30-050 {getIspSubdevs     :111} rkisp_mainpath_4x4sampling entity name is NULL
RTIsp3x          14:51:30-050 {getIspSubdevs     :122} rkisp_bypasspath_4x4sampling entity name is NULL
RTIsp3x          14:51:30-051 {getIspSubdevs     :133} isp_luma_path entity name is NULL
gkcam-->Nov  1 2024/14:34:02-main-82::RK_MPI_SYS_Init success!
cmpi             14:51:30-061 {mb_create_pool    :220} allocated buffer(this=0x75efc8, data=0xa631d000, size=614400, id=147)
cmpi             14:51:30-066 {mb_create_pool    :220} allocated buffer(this=0x75f1e8, data=0xa6287000, size=614400, id=148)
cmpi             14:51:30-067 {mb_create_pool    :220} allocated buffer(this=0x75f438, data=0xa61f1000, size=614400, id=149)
MpiAdapterEncode 14:51:30-069 {ma_encode_create  :1654} ringbuf buf_size 614400
cmpi             14:51:30-077 {Set_H264_Qp       :223} pstRcParam.s32FirstFrameStartQp: 26

cmpi             14:51:30-078 {Set_H264_Qp       :224} pstRcParam.stParamH264.u32StepQp: 8

cmpi             14:51:30-080 {Set_H264_Qp       :225} pstRcParam.stParamH264.u32MaxQp: 51

cmpi             14:51:30-082 {Set_H264_Qp       :226} pstRcParam.stParamH264.u32MinQp: 10

cmpi             14:51:30-084 {Set_H264_Qp       :227} pstRcParam.stParamH264.u32MaxIQp: 46

cmpi             14:51:30-084 {Set_H264_Qp       :228} pstRcParam.stParamH264.u32MinIQp: 24

cmpi             14:51:30-085 {Set_H264_Qp       :229} pstRcParam.stParamH264.s32DeltIpQp: 2

cmpi             14:51:30-086 {Set_H264_Qp       :230} pstRcParam.stParamH264.s32MaxReEncodeTimes: 1

cmpi             14:51:30-086 {Set_H264_Qp       :236} pstRcParam.s32FirstFrameStartQp: 26

cmpi             14:51:30-090 {Set_H264_Qp       :237} pstRcParam.stParamH264.u32StepQp: 8

cmpi             14:51:30-090 {Set_H264_Qp       :238} pstRcParam.stParamH264.u32MaxQp: 51

cmpi             14:51:30-090 {Set_H264_Qp       :239} pstRcParam.stParamH264.u32MinQp: 24

cmpi             14:51:30-090 {Set_H264_Qp       :240} pstRcParam.stParamH264.u32MaxIQp: 46

cmpi             14:51:30-092 {Set_H264_Qp       :241} pstRcParam.stParamH264.u32MinIQp: 24

cmpi             14:51:30-092 {Set_H264_Qp       :242} pstRcParam.stParamH264.s32DeltIpQp: 2

cmpi             14:51:30-092 {Set_H264_Qp       :243} pstRcParam.stParamH264.s32MaxReEncodeTimes: 1

/!\ SSH is already running
> Starting ADB...
/!\ ADB is already running
> Stopping Klipper...
gkcam-->Nov  1 2024/14:34:02-AcCameraBusinessThread-114::Cam.Path:/dev/video10

fmt.fmt.pix.bytesperline = 0
fmt.fmt.pix.sizeimage = 1843789
ioctl VIDIOC_S_FMT: Device or resource busy
/dev/video10 does not support memory mapping
/dev/video10 init_mmap failed!
VIDIOC_STREAMON failed: 16, Device or resource busy
gkcam-->Nov  1 2024/14:34:02-AcCameraBusinessThread-126::Camera /dev/video10 Capture failed!
Killing 2658 (./K3SysUi)
Killing 2727 (./gkcam)
Killing 2657 (./gkapi)
Killing 2634 (./gklib-a/tmp/unix_uds1printer.cfg)
> Preparing chroot...
> Starting Moonraker...
Killing 3291 (/usr/bin/python/usr/share/moonraker/moonraker/moonraker.py)
Killing 3942 (/usr/bin/python/usr/share/scripts/moonraker-proxy.py)
> Starting nginx...
Killing 854 (nginx: master process /usr/sbin/nginx)
Killing 856 (nginx: worker process)
> Starting mjpg-streamer...
Killing 2178 (/usr/bin/mjpg_streamer-iinput_uvc.so -d /dev/video10 -n -r 1280x720-ooutput_http.so -w /usr/share/mjpg-streamer/www)
> Restarting Klipper...
> Cleaning up...
Killing 2771 (/useremain/rinkhals/20241218_01/lib/ld-linux-armhf.so.3./usr/sbin/dropbear-F-E-a-p2222-P/tmp/dropbear_debug.pid-r./etc/dropbear/dropbear_rsa_host_key)

Rinkhals started
root@Rockchip:/userdata/app/gk# cd ..
```

Do I need to delete all the files and re install it?

**Comment by m3rguez0o** [comment]
these lines are red colored:
RTIsp3x          14:51:30-049 {getIspSubdevs     :100} rkisp_bypasspath entity name is NULL
RTIsp3x          14:51:30-050 {getIspSubdevs     :111} rkisp_mainpath_4x4sampling entity name is NULL
RTIsp3x          14:51:30-050 {getIspSubdevs     :122} rkisp_bypasspath_4x4sampling entity name is NULL
RTIsp3x          14:51:30-051 {getIspSubdevs     :133} isp_luma_path entity name is NULL

**Comment by ducati1198** [comment]
Same issue getting the 500 error in orca. Here are logs from 20241219 ans 20241223

[debug-bundle_20241223.zip](https://github.com/user-attachments/files/18230985/debug-bundle_20241223.zip)
[debug-bundle_20241219.zip](https://github.com/user-attachments/files/18230986/debug-bundle_20241219.zip)

**Comment by ducati1198** [comment]
The file get uploaded to the printer but doesn’t get started by the printer

![IMG_6444](https://github.com/user-attachments/assets/390b4886-0e95-4b62-b44a-8b69fa6065d1)

![IMG_6445](https://github.com/user-attachments/assets/6d23115b-71c9-4192-972b-d73ad485af3f)

![IMG_6447](https://github.com/user-attachments/assets/7d8e6754-b481-48b5-a01a-d864fc5d5367)

**Comment by m3rguez0o** [comment]
Here is the lag

**Comment by m3rguez0o** [comment]
Same here, it needs to be added to the job que and then you can "play".
Then there is a pause you need to resume.
But at this moment there is a problem with the temperature (140° instead of what you set while slicing) so the filament is pushing on the nozzle (I saw it moving ! ) because it's not hot enough.
It's not far but there is still some issues.

**Comment by m3rguez0o** [comment]
Here is the lag: 
https://we.tl/t-6rBqZrraJw

**Comment by jbatonnet** [comment]
Ok, so a couple of notes:
- According to your feedbacks, I must have messed up something with moonraker-proxy. I am reinstalling the last version to better understand what's happening
- The camera lag might be caused by the proxy looping like crazy, but there might be something else. I noticed Fluidd limits to ~5fps when it's not in focus. Now even Anycubic slicer only pushes 480p, I'll try to reduce the resolution to help the printer keeping up
- The debug bundle tool collect everything but the file I needed ([VERSION]/moonraker.log), so I updated it here: https://github.com/jbatonnet/Rinkhals/actions/runs/12472190440
If one of you can send me the updated debug-bundle, that would be super helpful.

Issues with the temperature, nozzle hitting the bed or other are related to the gcode and how the printer deals with that. Rinkhals doesn't change anything about that. The only thing is RInkhals "redirects" the print function to the one using the printer screen, the rest shouldn't be impacted.

Now, the moonraker-proxy is only active on port 7125, the original moonraker is still listening on port 7126.
If you are ever stuck with the proxy not working (I mean I'll fix it but in the meantime), you can "Add another printer" to Fluidd with port 7126 to access the original moonraker instance.

![image](https://github.com/user-attachments/assets/b8161056-d941-4cf9-9033-fe8c22c2e887)

**Comment by jbatonnet** [comment]
Ok got it, this is what happens when I'm trying to push updates too fast.
I'll test locally and I'll release a new update with a fix for the proxy, and the 480p webcam.
With all that I hope things will work for you guys, then I'll focus on some stabilization.

**Comment by m3rguez0o** [comment]
Thank you! I'll post the new logs tomorrow morning.

**Comment by ducati1198** [comment]
here you go logs files ith new debug tool
[debug-bundle_3734281952_19700101-190257.zip](https://github.com/user-attachments/files/18234578/debug-bundle_3734281952_19700101-190257.zip)

**Comment by ducati1198** [comment]
After updating to 20241223_02 everything looks too working fine. Print send by orca works quick, camera with no lag at 480p

**Comment by ducati1198** [comment]
![IMG_6452](https://github.com/user-attachments/assets/0f2fa863-2091-452a-ab37-c2eff3e81e0c)
![IMG_6453](https://github.com/user-attachments/assets/405574d0-2694-45ea-9893-444c72ce0203)

**Comment by m3rguez0o** [comment]
Hello,
Here is my debug bundle
[debug-bundle_3631682348_20241224-151538.zip](https://github.com/user-attachments/files/18237016/debug-bundle_3631682348_20241224-151538.zip)

**Comment by m3rguez0o** [comment]
Just updated to latest release 20241223_02, I have an issue after the reboot.
The green bar was ok then it rebooted and loaded the anycubic bar many times, then I get a 11407 error, saved the logs to the usb stick then the unofficial firmware splash, the it's stuck on the progress bar loaded at 100% but mainsail ui is accessible! 
I will now reboot the printer and I'm afraid of what will happening lol

**Comment by ducati1198** [comment]
The way i update is: update to factory firmware, after use ssh tool to rm -rf rinkhals folder and then reboot and after update with root. I prefer its way because its like a fresh install

**Comment by ducati1198** [comment]
> Just updated to latest release 20241223_02, I have an issue after the reboot. The green bar was ok then it rebooted and loaded the anycubic bar many times, then I get a 11407 error, saved the logs to the usb stick then the unofficial firmware splash, the it's stuck on the progress bar loaded at 100% but mainsail ui is accessible! I will now reboot the printer and I'm afraid of what will happening lol

Im on my 2 print and its working only deal is the new issue I made
